<PongGame>:
    BoxLayout:
        orientation: "vertical"
        Button:
            text: "hello"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
        Button:
            text: "how u doin"
